### ISSUE TITLE
Great resource. Now LICENSE!

### ISSUE THREAD

**Issue by ris-work** [elixir-webrtc/workshop#1]
Hey,
I hate to be _that guy_, I love the work being done here; this repository seems to be a great but a simple resource for those who are not only Elixir developers but for all the others who love WebRTC too.

This repository misses a LICENSE file.

Thank you for doing this, hopefully WebRTC will also include some Post Quantum resistant algorithms soon with DTLS 1.3+.

Regards,
Rishikeshan.

**Comment by mickel8** [comment]
Hi @ris-work, thanks, I added the license :)
